version: '3.8'

services:
  mediscreenwebapp:
    build:
      context: ./mediscreenWebapp
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - gatewayservice
    networks:
      - internal

  microservicerisk:
    build:
      context: ./microservice-risk
      dockerfile: Dockerfile
    networks:
      - internal

  microservicenote:
    build:
      context: ./microservice-note
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - internal
    environment:
      - "spring_data_mongodb_host=mongodb"

  microservicepatient:
    build:
      context: ./microservice-patient
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/mediscreen_patient?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  gatewayservice:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - internal

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - internal

volumes:
  mysql_data:
  mongodb_data_container:

networks:
  internal:
    driver: bridge
