version: '3.8'

services:
  mediscreenwebapp:
    build:
      context: ./mediscreenWebapp
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - mysql

  microservicepatient:
    build:
      context: ./microservice-patient
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/mediscreen_patient?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  gatewayservice:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
