version: '3.8'

services:
  mediscreenwebapp:
    build:
      context: ./mediscreenWebapp
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - mysql

  microservicenote:
    build:
      context: ./microservice-note
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    depends_on:
      - mongodb
    environment:
      - "spring_data_mongodb_host=mongodb"

  microservicepatient:
    build:
      context: ./microservice-patient
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/mediscreen_patient?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  gatewayservice:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db


volumes:
  mysql_data:
  mongodb_data_container:

networks:
  default:
    driver: bridge
